export type Car = {
    id: number,
    brand: string,
    model: string,
    image: string,
    registrationNumber: string,
    vin: string,
    mileage: number,
    price: number,
    insuranceValidUntil: string,
    inspectionValidUntil: string,
    firstRegistrationDate: string,
    vehicleType: string,
    yearOfProduction: number,
    engineCapacity: string,
    enginePower: string,
    fuelType: string,
    numberOfSeats: number,
    bodyType: string,
    transmission: string,
    numberOfDoors: number,
    notes: string,
    purchaseDate: string
}